-- MySQL Script generated by MySQL Workbench
-- Mon Oct 17 23:32:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paciente` (
  `id` INT NOT NULL,
  `cuit` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `tipoSangre` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `peso` FLOAT NULL,
  `altura` FLOAT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historia_clinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historia_clinica` (
  `id` INT NOT NULL,
  `fechaIngreso` DATE NULL,
  `descripcion_paciente` VARCHAR(250) NULL,
  `antecedentes` VARCHAR(45) NULL,
  `cirugiasPrevias` VARCHAR(45) NULL,
  `paciente_id` INT NOT NULL,
  PRIMARY KEY (`id`, `paciente_id`),
  INDEX `fk_historia_clinica_paciente1_idx` (`paciente_id` ASC) VISIBLE,
  CONSTRAINT `fk_historia_clinica_paciente1`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `mydb`.`paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medico` (
  `matricula` INT NOT NULL,
  `cuil` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  `genero` VARCHAR(45) NULL,
  `especialidad` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historia_clinica_por_medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historia_clinica_por_medico` (
  `historia_clinica_id` INT NOT NULL,
  `medico_matricula` INT NOT NULL,
  PRIMARY KEY (`historia_clinica_id`, `medico_matricula`),
  INDEX `fk_historia_clinica_has_medico_medico1_idx` (`medico_matricula` ASC) VISIBLE,
  INDEX `fk_historia_clinica_has_medico_historia_clinica1_idx` (`historia_clinica_id` ASC) VISIBLE,
  CONSTRAINT `fk_historia_clinica_has_medico_historia_clinica1`
    FOREIGN KEY (`historia_clinica_id`)
    REFERENCES `mydb`.`historia_clinica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historia_clinica_has_medico_medico1`
    FOREIGN KEY (`medico_matricula`)
    REFERENCES `mydb`.`medico` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vacuna_colocada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vacuna_colocada` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `fecha_colocacion` DATE NULL,
  `historia_clinica_id` INT NOT NULL,
  `medico_matricula` INT NOT NULL,
  PRIMARY KEY (`id`, `historia_clinica_id`, `medico_matricula`),
  INDEX `fk_vacuna_colocada_historia_clinica_por_medico1_idx` (`historia_clinica_id` ASC, `medico_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_vacuna_colocada_historia_clinica_por_medico1`
    FOREIGN KEY (`historia_clinica_id` , `medico_matricula`)
    REFERENCES `mydb`.`historia_clinica_por_medico` (`historia_clinica_id` , `medico_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consulta` (
  `id_consulta` INT NOT NULL,
  `fecha` VARCHAR(45) NULL,
  `tipoConsulta` VARCHAR(45) NULL,
  `observaciones` VARCHAR(45) NULL,
  `diagnostico` VARCHAR(45) NULL,
  `receta` VARCHAR(45) NULL,
  `proximaCita` VARCHAR(45) NULL,
  `medico_matricula` INT NOT NULL,
  `historia_clinica_id` INT NOT NULL,
  PRIMARY KEY (`id_consulta`, `medico_matricula`, `historia_clinica_id`),
  INDEX `fk_consulta_historia_clinica_has_medico1_idx` (`historia_clinica_id` ASC, `medico_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_consulta_historia_clinica_has_medico1`
    FOREIGN KEY (`historia_clinica_id` , `medico_matricula`)
    REFERENCES `mydb`.`historia_clinica_por_medico` (`historia_clinica_id` , `medico_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tratamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tratamiento` (
  `id` INT NOT NULL,
  `medicacion` VARCHAR(45) NULL,
  `dieta` VARCHAR(45) NULL,
  `cuidados_especiales` VARCHAR(45) NULL,
  `observaciones` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `historia_clinica_id` INT NOT NULL,
  `medico_matricula` INT NOT NULL,
  PRIMARY KEY (`id`, `historia_clinica_id`, `medico_matricula`),
  INDEX `fk_tratamiento_historia_clinica_has_medico1_idx` (`historia_clinica_id` ASC, `medico_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_tratamiento_historia_clinica_has_medico1`
    FOREIGN KEY (`historia_clinica_id` , `medico_matricula`)
    REFERENCES `mydb`.`historia_clinica_por_medico` (`historia_clinica_id` , `medico_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`examen_fisico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`examen_fisico` (
  `id` INT NOT NULL,
  `presion` VARCHAR(45) NULL,
  `peso` VARCHAR(45) NULL,
  `altura` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `historia_clinica_id` INT NOT NULL,
  `medico_matricula` INT NOT NULL,
  PRIMARY KEY (`id`, `historia_clinica_id`, `medico_matricula`),
  INDEX `fk_examen_fisico_historia_clinica_has_medico1_idx` (`historia_clinica_id` ASC, `medico_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_examen_fisico_historia_clinica_has_medico1`
    FOREIGN KEY (`historia_clinica_id` , `medico_matricula`)
    REFERENCES `mydb`.`historia_clinica_por_medico` (`historia_clinica_id` , `medico_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estudio_realizado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudio_realizado` (
  `id_estudio` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `resultado` VARCHAR(45) NULL,
  `fecha` VARCHAR(45) NULL,
  `archivo` VARCHAR(45) NULL,
  `historia_clinica_por_medico_historia_clinica_id` INT NOT NULL,
  `historia_clinica_por_medico_medico_matricula` INT NOT NULL,
  PRIMARY KEY (`id_estudio`, `historia_clinica_por_medico_historia_clinica_id`, `historia_clinica_por_medico_medico_matricula`),
  INDEX `fk_estudio_realizado_historia_clinica_por_medico1_idx` (`historia_clinica_por_medico_historia_clinica_id` ASC, `historia_clinica_por_medico_medico_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_estudio_realizado_historia_clinica_por_medico1`
    FOREIGN KEY (`historia_clinica_por_medico_historia_clinica_id` , `historia_clinica_por_medico_medico_matricula`)
    REFERENCES `mydb`.`historia_clinica_por_medico` (`historia_clinica_id` , `medico_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turno` (
  `id_turno` INT NOT NULL,
  `fecha` DATE NULL,
  `horario` DATE NULL,
  `lugar` VARCHAR(45) NULL,
  `motivo` VARCHAR(45) NULL,
  `paciente_id` INT NOT NULL,
  `medico_matricula` INT NOT NULL,
  PRIMARY KEY (`id_turno`, `paciente_id`, `medico_matricula`),
  INDEX `fk_turno_paciente1_idx` (`paciente_id` ASC) VISIBLE,
  INDEX `fk_turno_medico1_idx` (`medico_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_turno_paciente1`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `mydb`.`paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turno_medico1`
    FOREIGN KEY (`medico_matricula`)
    REFERENCES `mydb`.`medico` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
