# Generated by Django 3.2 on 2023-05-28 20:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('extras', models.FloatField(blank=True)),
                ('alta', models.DateField(default=datetime.datetime.now)),
                ('baja_duracion_dias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_h', models.DateField(default=datetime.datetime.now)),
                ('referencia_h', models.CharField(blank=True, max_length=20)),
                ('especialidad', models.CharField(max_length=30)),
                ('diagnostico', models.CharField(blank=True, max_length=50)),
                ('antecedentes', models.CharField(blank=True, max_length=255)),
                ('presion', models.CharField(blank=True, max_length=10)),
                ('peso', models.CharField(blank=True, max_length=10)),
                ('altura', models.CharField(blank=True, max_length=10)),
                ('prueba_diagnostica', models.CharField(blank=True, max_length=30)),
                ('medicacion', models.CharField(blank=True, max_length=50)),
                ('dieta', models.CharField(blank=True, max_length=100)),
                ('vacuna', models.CharField(blank=True, max_length=50)),
                ('proxima_visita', models.CharField(blank=True, max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('adjunto', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10)),
                ('nacimiento_m', models.DateField()),
                ('nombre_m', models.CharField(max_length=30)),
                ('apellido_m', models.CharField(max_length=30)),
                ('telefono_m', models.CharField(max_length=20)),
                ('direccion_m', models.CharField(max_length=40)),
                ('mail_m', models.CharField(max_length=30)),
                ('genero_m', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=20)),
                ('password_m', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuil', models.CharField(max_length=11)),
                ('nacimiento_p', models.DateField()),
                ('nombre_p', models.CharField(max_length=30)),
                ('apellido_p', models.CharField(max_length=30)),
                ('telefono_p', models.CharField(max_length=20)),
                ('direccion_p', models.CharField(max_length=40)),
                ('mail_p', models.CharField(max_length=30)),
                ('genero_p', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=9)),
                ('sangre', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('0+', '0+'), ('0-', '0-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('password_p', models.CharField(max_length=20)),
                ('premium', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('duracion_meses', models.IntegerField()),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicioFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.factura')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.paciente')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.historia')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.medico')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.paciente')),
            ],
        ),
    ]
