# Generated by Django 3.2.15 on 2023-05-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuil', models.CharField(max_length=100)),
                ('name_p', models.CharField(max_length=100)),
                ('nacimiento', models.DateField(max_length=100)),
                ('apellido_p', models.CharField(max_length=100)),
                ('telefono_p', models.CharField(max_length=100)),
                ('direccion_p', models.CharField(max_length=100)),
                ('genero_p', models.CharField(max_length=100)),
                ('password_p', models.CharField(max_length=100)),
                ('premium_p', models.CharField(max_length=100)),
                ('mail_p', models.CharField(max_length=100)),
            ],
        ),
    ]
