# Generated by Django 3.2 on 2023-06-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='alta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
